# Basics in Julia 2

We now know about basic variables and basics maths. However it is often more convenient to handle a collection of elements. For that we can use Arrays/Vectors and Matrices in Julia!

## 1. Vectors

#### 1.1 Creating vectors

A Vector is an array of dimension 1. The most basic way to define a vector in Julia is to use the square brackets and separate each value with a comma as follows:

In [1]:
v = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [2]:
v = [1,2,3]
typeof(v)

Vector{Int64} (alias for Array{Int64, 1})

The type of an array in Julia is defined as `Vector{T}` where `T` is the type of the elements in the Vector. For example in the example above, we put `Int64` (integers) in the Vector. As a result, the variable `v` has the type `Vector{Int64}`.

In [3]:
w = [2.2, 2.3, 5.7, 7.1] # Here, we have Float64 in our vector...

4-element Vector{Float64}:
 2.2
 2.3
 5.7
 7.1

In [4]:
typeof(w) # ... consequently, the type of w is Vector{Float64}

Vector{Float64} (alias for Array{Float64, 1})

You may sometimes see `Array{T, 1}` instead of `Vector{T}`. These two are equivalent in Julia: a vector is an array of dimension 1.

You can add elements of different types in a Vector. Just like for variables, Julia will attribute the appropriate type to the vector by default.

In [5]:
v = [1, 2.5, 4, 7, 5.7] # A mix of Int64 and Float 64...

5-element Vector{Float64}:
 1.0
 2.5
 4.0
 7.0
 5.7

In [6]:
typeof(v) # ... will result in a Vector{Float64}, as Int64 can be represented as Float64.

Vector{Float64} (alias for Array{Float64, 1})

In [7]:
w = ["Hi", true, 5.4] # A mix of a lot of different things...

3-element Vector{Any}:
     "Hi"
 true
    5.4

In [8]:
typeof(w) # ... will result in a Vector{Any}

Vector{Any} (alias for Array{Any, 1})

The keyword `Any` basically means that the type can be anything. It is often **something better to avoid** however! The reason is that Julia will have to check the type of each element before performing an operation on it, to evaluate what it is allowed to do or not on this element. This often leads to slower code.

There are a few functions that are helpful to create particular arrays in Julia:

In [9]:
zeros(10) # creates a vector of size 10 containing only 0s (as Float64)

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [10]:
ones(10) # creates a vector of size 10 containing only 1s (as Float64)

10-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [11]:
# for both of these functions, you can specify the type of the 0s and 1s

zeros(Int64, 10)

10-element Vector{Int64}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [12]:
fill(10,5) # creates an array of size 5 containing 10s (this time by default as Int64!!!)

5-element Vector{Int64}:
 10
 10
 10
 10
 10

Remember that you can always check the documentation if you are unsure of how to use a function, and what parameters you can specify for the functions! When in doubt, it's the right thing to do.

Another way to create vectors is to use something sometimes refered to as *array comprehension*. It uses the concept of for loops to create vectors. There will be more details on loops later, but for now here are a few examples. I'm sure you will get the gist of it:

In [13]:
[i for i in 1:5] # equivalent to [1, 2, 3, 4, 5]

#=
start:stop, where start and stop are two integers, is a range.
It is equivalent to start, start+1, start+2, ..., stop-2, stop-1, stop. More on that later!
=#

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [14]:
# You can play around with more complex functions as well

[factorial(i) + i for i in 1:7]

7-element Vector{Int64}:
    2
    4
    9
   28
  125
  726
 5047

In [15]:
# You can add conditions on the indices as well

[i for i in 1:10 if i % 2 == 1] # creates an array with odd numbers between 1 and 10

#=
Note: this uses the syntax of if statements that we have not encountered yet.
For now, just know that it works by adding if followed by a boolean expression (true or false).
=#

5-element Vector{Int64}:
 1
 3
 5
 7
 9

In [16]:
# You can also have multiple indices

[j for i in 1:2 for j in 1:4] # Note the priority of the indices here: for each i in order, the second for loop is executed

8-element Vector{Int64}:
 1
 2
 3
 4
 1
 2
 3
 4

In [17]:
[i + j for i in 1:2 for j in -2:4]

14-element Vector{Int64}:
 -1
  0
  1
  2
  3
  4
  5
  0
  1
  2
  3
  4
  5
  6

Finally, we sometimes know in advance the size of a vector but we do not know the values that should go inside the vector yet. In such cases, it can be useful to create an uninitialized vector. Let's make an uninitialized vector of size 10 that will contains integers:

In [18]:
v = Vector{Int64}(undef, 10)

10-element Vector{Int64}:
 4774779152
 4436076496
 4425667664
 4435907024
 4478669616
 4478670096
 4478670144
 4435906128
 4435906192
 4435906256

Note that you have to specify the type of the vector yourself this time, since Julia do not know what elements constitutes your vector yet. The keywork `undef` means that the elements of the vector are not defined yet. As you can see, there are still some values assigned in each cell of the vector, but those are random and do not have a particular meaning - you can ignore them and fill your vector as you like.

#### 1.2 Accessing and modifying the elements of a vector

To access one element of a vector, use the square backets together with the index of the element you want to access. Note that in Julia, **indexing starts at 1**, not 0.

In [19]:
v = [1,5,4,7,6]
v[3] # third element of the vector

4

To access the last element of a vector, the keywork `end` can be used in place of the index. Moreover, you can use basic operations with the keyword end, e.g. do access the second to last element, ect.

In [20]:
v = [1,5,4,7,6]
v[end] # last element of the vector

6

In [21]:
v = [1,5,4,7,6]
v[end - 1] # you can do basic operations with end as well

7

You can access multiple elements of a vector at once by using a range (`start:stop`) and even a vector of indices.

In [22]:
# with a range
v = [5,2,4,1,5,4,8,7,5,9,6,5,3,2,1] # size is 15

v[3:5] # returns a sub-vector made of the elements at indices 3, 4, and 5

3-element Vector{Int64}:
 4
 1
 5

In [23]:
# with a vector of indices
v = [5,2,4,1,5,4,8,7,5,9,6,5,3,2,1] # size is 15

indices = [1,3,12,15]
v[indices] # returns a sub-vector made of the elements at indices 1, 3, 12, and 15

4-element Vector{Int64}:
 5
 4
 5
 1

You can as well modify the elements of a vector using that. For example:

In [24]:
v = [1,5,4,7,6]
v[3] = 9 # the third element of v becomes 9
println(v)

[1, 5, 9, 7, 6]


In [25]:
v = [5,2,4,1,5,4,8,7,5,9,6,5,3,2,1]
v[3:5] = [99,99,99]
println(v)

[5, 2, 99, 99, 99, 4, 8, 7, 5, 9, 6, 5, 3, 2, 1]


When changing the value of multiple elements at once, you have to make sure that you are giving the same number of values than elements you are trying to modify! For example, if you try to assign one value to a sub-vector of size three, you will get the following error:

In [26]:
v = [5,2,4,1,5,4,8,7,5,9,6,5,3,2,1]
v[3:5] = [99]

DimensionMismatch: DimensionMismatch: tried to assign 1 elements to 3 destinations

#### 1.3 Dynamically changing the size of a vector

It is possible to add elements to vectors using the functions `push!` and `pushfirst!`.

In [27]:
# at the back

v = [5,4,1,2]
push!(v, 10)
println(v)

[5, 4, 1, 2, 10]


In [28]:
# at the front

v = [5,4,1,2]
pushfirst!(v, 10)
println(v)

[10, 5, 4, 1, 2]


Similarly, it is possible to remove elements from vectors as well with the functions `pop!` and `popfirst!`. These two functions also returns the extracted value, which you can store in a variable.

In [29]:
# at the back

v = [5,4,1,2]
pop!(v)
println(v)

[5, 4, 1]


In [30]:
# at the front

v = [5,4,1,2]
popfirst!(v)
println(v)

[4, 1, 2]


In [31]:
# extracted value

v = [5,4,1,2]
extractedValue = pop!(v)
println(v)
println(extractedValue)

[5, 4, 1]
2


In [32]:
# at a given index

v = [5,4,1,2]
splice!(v, 3)
println(v)

[5, 4, 2]


You can merge two vectors by using the function `append`.

In [33]:
v1 = [1,2,3,4]
v2 = [5,6]

append!(v1, v2)

println(v1)
println(v2)

[1, 2, 3, 4, 5, 6]
[5, 6]


You may notice that these function have this unsusual `!` in their name. It in fact comes from a Julia naming convention: some functions that modify a vector have this exclamation marks.

#### 1.4 Apply a function to all elements of a vector

It is sometimes handy to apply a function to all elements of a vector. There are multiple ways to do so. For basic operator, *broadcasting* can be used: simply put a `.` before the operator or after the name of the function you want to apply.

For example, let's try to deccrease by 1 all values in the vector `v = [2,4,8,16]`.

In [34]:
# We cannot just say v - 1, this doesn't work and raise an error
v = [2,4,8,16]
v - 1

MethodError: MethodError: no method matching -(::Vector{Int64}, ::Int64)
For element-wise subtraction, use broadcasting with dot syntax: array .- scalar

Closest candidates are:
  -(!Matched::Base.CoreLogging.LogLevel, ::Integer)
   @ Base logging.jl:132
  -(!Matched::Complex{Bool}, ::Real)
   @ Base complex.jl:326
  -(!Matched::BigInt, ::Union{Int16, Int32, Int64, Int8})
   @ Base gmp.jl:557
  ...


In [35]:
# We have to use broadcasting to apply -1 to all elements
v = [2,4,8,16]
v .- 1

4-element Vector{Int64}:
  1
  3
  7
 15

In [36]:
# it works with functions as well
v = [2,4,8,16]
exp.(v)

4-element Vector{Float64}:
    7.38905609893065
   54.598150033144236
 2980.9579870417283
    8.886110520507872e6

In [37]:
# You can combine them to make more complex expressions
v = [2,4,8,16]
w = 2 .* sqrt.(v) .+ 1 # we apply 2 * sqrt(.) + 1 to each element of v
println(w)

[3.8284271247461903, 5.0, 6.656854249492381, 9.0]


When making more complex expressions like in the previous example, it can quickly becomes harder to read. Another way to do it is to use the function `map`, that works by defining an expression and applying it to each element of the vector.

In [38]:
v = [2,4,8,16]
w = map(x -> 2 * sqrt(x) + 1, v)
println(w)

[3.8284271247461903, 5.0, 6.656854249492381, 9.0]


Note that broadcasting and `map` do *not* modify the initial vector, they return a new one!

#### 1.5 Making a copy of a vector

Copying a basic variable with a basic type is very easy and straightforward:

In [39]:
a = 5
b = a # b is a copy of a

a = 2 # we modify a
b += 3 # we do some operations on b

println("a = ", a)
println("b = ", b)

a = 2
b = 8


We make a copy of `a` and store it in `b` by using `a = b`. Then, we can make modifications on `a` and `b` independently. In the case of vectors, the situation is a bit different!

In [40]:
a = [1,2,3,4]
b = a

b[2] = 0

println("a = ", a)
println("b = ", b)

a = [1, 0, 3, 4]
b = [1, 0, 3, 4]


If we use the same copy procedure, when a modification on `b` also changes `a`!!! This is due to the way vectors are represented and handled in the computer. If you want to make an actual copy of a vector, you have to use the function `copy`.

In [41]:
a = [1,2,3,4]
b = copy(a)

b[2] = 0

println("a = ", a)
println("b = ", b)

a = [1, 2, 3, 4]
b = [1, 0, 3, 4]


**Exercise 1**

Create the vector `myvct = [2, 7, 4]`.

1. Add the value 99 to the end of this vector.
2. Remove the first value of this vector.

**Exercise 2**

Use an array comprehension to create an array that stores the squares of all integers between 1 and 100.

#### 1.6 Useful functions for vectors

There are plenty of useful functions for vectors. Here are a few of them (see documentation for more details):

In [44]:
# length of a vector

v = [5,4,8,5,4,3,4,9]
length(v)

8

In [45]:
# get the minimum and maximum

v = [5,4,8,5,4,3,4,9]
println(minimum(v))
println(maximum(v))

3
9


In [46]:
# find the first occurence of a value in a vector

v = [5,4,8,5,4,3,4,9]
findfirst(x -> x == 8, v) # requires a boolean function as the first parameter

3

In [47]:
# sort a vector

v = [5,4,8,5,4,3,4,9]
sort!(v) # Useful tip: there is a variant called sort (no exclamation mark) that do not modify v directly
println(v)

[3, 4, 4, 4, 5, 5, 8, 9]


In [48]:
# get the sorted indices

v = [5,4,8,5,4,3,4,9]
sortperm(v)

8-element Vector{Int64}:
 6
 2
 5
 7
 1
 4
 3
 8

## 2. Matrices

Matrices are very similar to vectors, the main difference being that these are two dimensional. There are two ways to consider matrices in Julia: using the actual `Matrix` type (multidimentional array), or using vectors of vectors.

#### 2.1 Matrix

The most basic way to define a matrix is to use square brackets. Each row is separated by a `;`, and values within each row are separated by a space.

In [49]:
M = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [50]:
M = [1 2; 3 4]
typeof(M) # see the type

Matrix{Int64} (alias for Array{Int64, 2})

You can define particular or undefined matrices the same way as for vectors, except that you have to specify two dimensions now.

In [51]:
zeros(4,6)

4×6 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [52]:
ones(2,8)

2×8 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [53]:
fill(2.5, 3, 1)

3×1 Matrix{Float64}:
 2.5
 2.5
 2.5

In [54]:
M = Matrix{Int64}(undef, 4, 4)

4×4 Matrix{Int64}:
 0  0  0  1
 0  0  0  0
 0  1  1  1
 0  0  1  0

To access elements of a Matrix, use the square brackets and the two indices separated by a `,`. You can again access the last element of a dimension using the keywork `end`. You can also select multiple indices at once for one dimension using `a:b`. Finally, you can select all indices for one dimension using `:`.

In [55]:
M = [5 8 7 9; 4 5 1 2; 8 7 5 0; 5 8 8 8; 45 1 2 1]

5×4 Matrix{Int64}:
  5  8  7  9
  4  5  1  2
  8  7  5  0
  5  8  8  8
 45  1  2  1

In [56]:
M[1,3] # M[row, column]

7

In [57]:
M[3,2:end] # row 3, columns 2 to the end. The result is a vector!

3-element Vector{Int64}:
 7
 5
 0

In [58]:
M[:, 3] # returns column 3 as a vector

5-element Vector{Int64}:
 7
 1
 5
 8
 2

Broadcasting and `map` work the same way as for vectors.

In [59]:
M = [5 8 7 9; 4 5 1 2; 8 7 5 0; 5 8 8 8; 45 1 2 1]
M .* 2 # multiply all elements by two

5×4 Matrix{Int64}:
 10  16  14  18
  8  10   2   4
 16  14  10   0
 10  16  16  16
 90   2   4   2

In [60]:
M = [5 8 7 9; 4 5 1 2; 8 7 5 0; 5 8 8 8; 45 1 2 1]
map(x -> 2 * x, M) # does the same thing using map

5×4 Matrix{Int64}:
 10  16  14  18
  8  10   2   4
 16  14  10   0
 10  16  16  16
 90   2   4   2

There are also many functions that can be used for matrices. A difference with vectors however is that you get the size of the matrix using the function `size`.

In [61]:
M = [5 8 7 9; 4 5 1 2; 8 7 5 0; 5 8 8 8; 45 1 2 1]
s = size(M)
println(s)

(5, 4)


In [62]:
M = [5 8 7 9; 4 5 1 2; 8 7 5 0; 5 8 8 8; 45 1 2 1]
s1, s2 = size(M)
println(s1)
println(s2)

5
4


Finally, you have to be careful when making copy here as well: use the `copy` function.

In [63]:
# Doesn't make a real copy

M = [5 8 7 9; 4 5 1 2; 8 7 5 0; 5 8 8 8; 45 1 2 1]
Mcopy = M

Mcopy[2, 2] = 500

println(M)
println(Mcopy)

[5 8 7 9; 4 500 1 2; 8 7 5 0; 5 8 8 8; 45 1 2 1]
[5 8 7 9; 4 500 1 2; 8 7 5 0; 5 8 8 8; 45 1 2 1]


In [64]:
# Makes a proper copy

M = [5 8 7 9; 4 5 1 2; 8 7 5 0; 5 8 8 8; 45 1 2 1]
Mcopy = copy(M)

Mcopy[2, 2] = 500

println(M)
println(Mcopy)

[5 8 7 9; 4 5 1 2; 8 7 5 0; 5 8 8 8; 45 1 2 1]
[5 8 7 9; 4 500 1 2; 8 7 5 0; 5 8 8 8; 45 1 2 1]


#### 2.2 Vectors of vectors

You can also represent Matrices as Vectors containing vectors. The main advantage is that each "row" can have a different number of "columns", but some functions on matrices cannot be used anymore (e.g. the size). What is the best representation really depends on what you are trying to achieve.

A vector of vector is a regular vector where each element is a vector itself. You can see that as a vector of type Vector{T}.

In [65]:
M = [[2,5,4], [5,4], [4,8,5]]

3-element Vector{Vector{Int64}}:
 [2, 5, 4]
 [5, 4]
 [4, 8, 5]

Because we `M` is a vector, and each element of `M` is a vector itself, we will use double square brackets to access elements.

In [66]:
M = [[2,5,4], [5,4], [4,8,5]]
M[2][2]

4

A vector of vectors is a vector, which means that everything that we saw about vectors previously applies here!... With only one difference: the copy operator.

In [67]:
M = [[2,5,4], [5,4], [4,8,5]]
Mcopy = copy(M)

Mcopy[3][1] = 500

println(M)
println(Mcopy)

[[2, 5, 4], [5, 4], [500, 8, 5]]
[[2, 5, 4], [5, 4], [500, 8, 5]]


Even though we used copy, the change in only one of the vectors is applied to both... Again that's because of how vectors are represented in the computer in Julia. In this case, we use the function called `deepcopy`.

In [68]:
M = [[2,5,4], [5,4], [4,8,5]]
Mcopy = deepcopy(M)

Mcopy[3][1] = 500

println(M)
println(Mcopy)

[[2, 5, 4], [5, 4], [4, 8, 5]]
[[2, 5, 4], [5, 4], [500, 8, 5]]


**Exercise 3**

1. Create the following matrix `mymtx` :
$\left(\begin{array}{cccc}
  5 & 8 & 3 & 6 \\
 10 & 4 & 6 & 1 \\
  7 & 5 & 2 & 8
\end{array}\right)$ 
2. assign the 3rd line of `mymtx` into a vector named `Vline`
3. copy the 2nd column of `mymtx` into a vector named `Vcolumn`
4. copy `mymtx` into an other matrix named `cpmtx`
5. assign the value 0 to `cpmtx[2,3]`
6. display `mymtx` and `cpmtx`
7. transpose `nwmtx` (hint: check the `transpose` function) 

**Exercise 4**

You have to solve an optimization model for your company. The model decides whether your company should launch a production or not in each month of the coming year. In order to run the model, you need to know the production cost and the inventory cost for each month, and forecasted demand for the coming year. You obtain the following data from the other departments:

- `D = [2,1,2,4,7,10,11,11,7,2,3,4]` from the forecasting department (demand)
- `P = [12,12,11,15,15,18,18,17,12,14,10,13]` from the production department (production cost)
- `I = [6,5,5,5,7,8,8,10]` from the inventory department (inventory cost)



For each array obtained, the first index represents January, the second is February, ect. The inventory department told you that due to a change in the warehouses, they had data available only until August. However, they will provide you with the missing data soon. 

1. Instead of having to manage three different arrays in your code, you prefer to merge them into a single array. Create an array `data` such that the first element is D, the second element is P, and the third element is I.

2. The inventory department finally obtained the missing data and sent you the following array: `ISepDec = [7,4,4,6]`, corresponding to the inventory costs for the months of Septembre, October, November, and December. Add the newly obtained data to the inventory cost array in `data`.

3. In your model, among many different variables, there are binary variables $y_i$ such that $y_i = 1$ if the production line is opened in month $i$, $y_i = 0$ otherwise. After solving the model, the solver returns you the following values for $y_i$: `y = [0.0,1.0,1.000000001,1.0000000001,0.0,-0.0000000001,0.0,0.0,0.999999999,-0.00000001,1.0,0.0]`. Although each value of `y` should be either `0` or `1`, some values are slightly above or below. This is due to the fact that computers sometimes have numerical errors. In order to present your result to the company, clean up `y` by rounding each of its elements to the nearest integer value.

4. Due to changes in the market conditions, the forecast department informs you that the forecasted demand from October to December is now given by `DOctDec = [3,4,8]`. Create a copy of `data` in an array called `correctedData`, and update `correctedData` with the new demand vector.

5. `data` is kept for history, and `correctedData` will be used to resolve the model. Print both `data` and `correctedData`, and make sure that `data` has a demand of `2`, `3`, and`4` for October, November and December respectively.

There are other objects that can be used to store collections of elements, such as `tuple`, `dictionary`, `set`, ect... We won't really use them in this course, but at least you know that these exist.